// frontend/apartment-management/src/app/shared/components/user-avatar/user-avatar.component.ts
import { Component, Input, signal } from '@angular/core';
import { SecureImageComponent } from '../secure-image/secure-image.component';
import { ImageLightboxComponent } from '../image-lightbox/image-lightbox.component';

/**
 * User avatar shown wherever a user is listed: renders the profile picture when one exists
 * (with the standard click-to-zoom lightbox), otherwise the user's initials.
 */
@Component({
  selector: 'app-user-avatar',
  standalone: true,
  imports: [SecureImageComponent, ImageLightboxComponent],
  template: `
    @if (pictureUrl) {
      <app-secure-image [src]="pictureUrl" [alt]="name" imgClass="user-avatar__img"
        [clickable]="zoom" (imageClick)="lightboxOpen.set(true)"></app-secure-image>
      @if (zoom) {
        <app-image-lightbox [open]="lightboxOpen()" [src]="pictureUrl"
          (closed)="lightboxOpen.set(false)"></app-image-lightbox>
      }
    } @else {
      <div class="user-avatar__initials">{{ initials }}</div>
    }
  `,
  styles: [`
    :host { display: inline-block; }
    :host, .user-avatar__img, .user-avatar__initials {
      width: var(--avatar-size, 40px);
      height: var(--avatar-size, 40px);
    }
    .user-avatar__img { border-radius: 50%; }
    .user-avatar__initials {
      border-radius: 50%;
      background: var(--primary-light, #1976d2);
      color: #fff;
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: 700;
      font-size: calc(var(--avatar-size, 40px) * 0.38);
      text-transform: uppercase;
    }
  `],
})
export class UserAvatarComponent {
  @Input({ required: true }) name = '';
  @Input() pictureUrl: string | null | undefined;
  /** Click-to-zoom on the picture; disable in dense contexts. */
  @Input() zoom = true;

  readonly lightboxOpen = signal(false);

  get initials(): string {
    return this.name
      .split(' ')
      .filter(Boolean)
      .map(part => part[0])
      .join('')
      .slice(0, 2);
  }
}

// mobile/src/shared/components/UserAvatar.tsx
import React, { useState } from 'react';
import { View, Text, Image, TouchableOpacity, StyleSheet } from 'react-native';
import { resolveFileUrl } from '../../camera/imageUpload';
import { ImageZoomModal } from './ImageZoomModal';
import { colors } from '../../theme/colors';
import { typography } from '../../theme/typography';

interface UserAvatarProps {
  name: string;
  /** App-relative profile picture URL (e.g. "files/profile-pictures/..."). */
  pictureUrl?: string | null;
  size?: number;
  /** Tap-to-zoom on the picture; disable in dense contexts. */
  zoom?: boolean;
}

/**
 * User avatar shown wherever a user is listed: renders the profile picture when one exists
 * (with the standard tap-to-zoom modal), otherwise the user's initials.
 */
export function UserAvatar({ name, pictureUrl, size = 40, zoom = true }: UserAvatarProps) {
  const [zoomVisible, setZoomVisible] = useState(false);

  const initials = name
    .split(' ')
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part.charAt(0).toUpperCase())
    .join('');

  const circle = { width: size, height: size, borderRadius: size / 2 };

  if (!pictureUrl) {
    return (
      <View style={[styles.initialsCircle, circle]}>
        <Text style={[styles.initialsText, { fontSize: size * 0.38 }]}>{initials || '?'}</Text>
      </View>
    );
  }

  const uri = resolveFileUrl(pictureUrl);
  return (
    <>
      <TouchableOpacity
        disabled={!zoom}
        onPress={() => setZoomVisible(true)}
        accessibilityLabel={`${name} profile picture`}
      >
        <Image source={{ uri }} style={circle} />
      </TouchableOpacity>
      {zoom && (
        <ImageZoomModal visible={zoomVisible} uri={uri} onClose={() => setZoomVisible(false)} />
      )}
    </>
  );
}

const styles = StyleSheet.create({
  initialsCircle: {
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  initialsText: {
    color: '#FFF',
    fontWeight: typography.fontWeight.bold,
  },
});
